spring:
  application:
    name: monitoreo-service
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    registerWithEureka: false
    #fetchRegistry: false
